name: env

channels:
- https://conda.anaconda.org/faph
- https://conda.anaconda.org/openhydrology

dependencies:
- python=3.4.*
- floodestimation=0.7.0
- jinja2
- psycopg2
- flask=0.10.*
- flask-restful=0.3.4
- pip:
  - gunicorn
  - celery
  - flask-cors
  - Flask-SSLify

