name: env

channels:
- https://conda.anaconda.org/faph
- https://conda.anaconda.org/openhydrology

dependencies:
- python=3.4.*
- flask=0.10.*
- flask-restful=0.3.4
- autostatistical=0.8.0
- pip:
  - gunicorn
  - celery
