name: env

channels:
- https://conda.anaconda.org/faph
- https://conda.anaconda.org/openhydrology
- https://conda.anaconda.org/openhydrology/channel/dev

dependencies:
- python=3.4.*
- appdirs
- floodestimation=0.6.1
- jinja2
- psycopg2
- flask=0.10.*
- flask-restful=0.3.4
- pip:
  - gunicorn
  - celery
  - flask-cors
